name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      STAGING_URL: ${{ vars.STAGING_URL }}
      EMAIL_VALID: ${{ vars.EMAIL_VALID }}
      PASS_VALID: ${{ vars.PASS_VALID }}
      CYPRESS_TOKEN: ${{ vars.CYPRESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress Run Script
        uses: cypress-io/github-action@v5
        with:
          build: npm install
          browser: chrome
          start: npx cypress run --spec cypress/e2e/login.cy.js --record --key $CYPRESS_TOKEN
