name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    env:
      CYPRESS_TOKEN: ${{ vars.CYPRESS_TOKEN }}
      STAGING_URL: ${{ vars.STAGING_URL }}
      STAGING_ADMIN_URL: ${{ vars.STAGING_ADMIN_URL }}
      EMAIL_VALID: ${{ vars.EMAIL_VALID }}
      PASS_VALID: ${{ vars.PASS_VALID }}
      EMAIL_NOT_VALID: ${{ vars.EMAIL_NOT_VALID }}
      EMAIL_NOT_REGISTER: ${{ vars.EMAIL_NOT_REGISTER }}
      PASS_NOT_VALID: ${{ vars.PASS_NOT_VALID }}
      EMAIL_ADMIN: ${{ vars.EMAIL_ADMIN }}
      PASS_ADMIN: ${{ vars.PASS_ADMIN }}
    environment:
      name: TurnkeyID
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress Run Script
        uses: cypress-io/github-action@v5
        with:
          build: npm install
          browser: chrome
          parallel: true
          command: npx cypress run --env STAGING_URL=${{env.STAGING_URL}},STAGING_ADMIN_URL=${{env.STAGING_ADMIN_URL}},EMAIL_VALID=${{env.EMAIL_VALID}},PASS_VALID=${{env.PASS_VALID}},EMAIL_NOT_VALID=${{env.EMAIL_NOT_VALID}},EMAIL_NOT_REGISTER=${{env.EMAIL_NOT_REGISTER}},PASS_NOT_VALID=${{env.PASS_NOT_VALID}},EMAIL_ADMIN=${{env.EMAIL_ADMIN}},PASS_ADMIN=${{env.PASS_ADMIN}} --record --key ${{env.CYPRESS_TOKEN}}
