name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment:
      name: TurnkeyID
    steps:
      - name: Check ENV
        run: echo "$STAGING_URL"
          echo "$EMAIL_VALID"
          echo "$PASS_VALID"
